# docker-compose.yml (в корне репозитория)
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # эти имена должны совпадать с теми, что читает твой backend/config.py
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydb
      - MONGO_URI=mongodb://mongo:27017/mongo_train
      - MONGO_DBNAME=mongo_train
      - SECRET_KEY=supersecretkey
      - ADMIN_EMAILS=admin@example.com
    depends_on:
      - mongo
      - postgres
    
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend        
      dockerfile: Dockerfile
    container_name: mongo-trainer-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app          
      - /app/node_modules        
    depends_on:
      - backend

  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql

  mongo:
    image: mongo:5
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./docker/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js

volumes:
  pgdata:
